ci: replace travis with github action
expressjs/multer pull request #1259
Opened 2024-05-10 15:07 UTC by inigomarquinez

This PR migrates the CI pipeline from travis to GitHub actions and adds node version 11 to 22 to the matrix.

The travis project should be removed after merging the PR (see [here](https://github.com/inigomarquinez/expressjs-multer/actions/runs/9034165622)).

The CI pipeline works in my local fork.

Related to https://github.com/jshttp/http-errors/issues/108

2024-05-10 18:21 UTC, UlisesGascon approved these changes
LGTM!

2024-05-29 04:02 UTC, ctcpip requested changes

2024-05-29 04:02 UTC, ctcpip commented on package.json
> +    "test": "mocha --reporter spec --bail --exit --check-leaks test/",
```suggestion
    "test": "standard && mocha --reporter spec --bail --exit --check-leaks test/",
```

2024-05-29 04:18 UTC, ctcpip commented on package.json
> +    "nyc": "^15.1.0",
these should be devDependencies, along with standard and maybe others

2024-06-03 15:36 UTC, ctcpip requested changes
`package-lock.json`  should not be added

2024-06-13 15:17 UTC, inigomarquinez commented
@UlisesGascon , @ctcpip 

Is this PR ready to be merged? Do you need me to do something else?

2024-06-13 16:14 UTC, ctcpip approved these changes

2024-06-13 17:17 UTC, merged