fixes(#1283): Add documentation for Multer functions
expressjs/multer pull request #1284
Opened 2024-11-11 20:28 UTC by arham-sayyed

### PR Title:
`docs: Add documentation for Multer functions`

### Description:
This pull request adds comprehensive documentation for various Multer functions, improving code readability and helping developers understand the purpose and usage of each function. The following functions have been documented:

- `allowAll`
- `Multer.prototype.single`
- `Multer.prototype.array`
- `Multer.prototype.fields`
- `Multer.prototype.none`
- `Multer.prototype.any`
- `Multer.prototype._makeMiddleware`
- `wrappedFileFilter`

These additions aim to enhance the clarity of the codebase and provide better insight into the functionality of the Multer library.

### Changes:
- Added JSDoc comments for all relevant functions.
- Provided detailed descriptions of each function's behavior and parameters.
- Improved inline documentation to support better developer experience.

### Motivation and Context:
Clear documentation helps developers understand how to use the Multer library effectively. This PR aims to improve the usability and maintainability of the code.

### Type of Change:
- Documentation update.

### How to Test:
No testing required, as this is purely a documentation update. Review the code for clarity and accuracy of the added comments.

2024-12-26 08:21 UTC, IamLizu commented on index.js
> + *   - `err` (Error, if any, or `null` to allow the file)
@arham-sayyed hey 👋 

Can you please help me understand this line according the code written in the function?

2024-12-27 07:57 UTC, IamLizu commented
This adds a lot of changes, in internal methods as well. While the work is appreciated, I suggest changing the PR to _DRAFT_ so that we do not accidentally land it before its ready as there's so much jsDoc to review.

2025-01-04 11:26 UTC, arham-sayyed commented on index.js
> + *   - `err` (Error, if any, or `null` to allow the file)
Hey 👋  

Sure! Let me explain line 13:  

```js
 * - `err` (Error, if any, or `null` to allow the file)
```

This describes the first parameter of the callback function (`cb`) used in the `allowAll` function. The `err` parameter is intended to indicate if there's an error that should prevent the file from being processed.  

- If you pass `null` as the `err` value (as done in `cb(null, true)`), it means there's no error, and the file is allowed to proceed.  
- If you pass an `Error` object instead of `null`, it will stop the processing of that specific file and trigger an error in the file upload flow.  

Essentially, this mechanism allows you to handle file validation or other conditions dynamically, depending on your use case. In this case, since `allowAll` is a default filter that accepts all files, we simply pass `null` for `err` to indicate no error. 😊  

Let me know if you have any further questions!

2025-06-02 03:23 UTC, bjohansebas commented on index.js
> +    /**
```suggestion
/**
```

2025-06-02 03:26 UTC, bjohansebas approved these changes
LGTM,  thanks!

2025-06-27 20:17 UTC, IamLizu requested changes
Looks almost good to me.

2025-06-27 20:17 UTC, IamLizu commented on storage/memory.js
> + * Handles the file processing (storing the file in memory as a buffer).
Since we are doing this, maybe add an explicit @constructor tag?

```js
/**
 * @constructor
 * @param {Object} opts
 * …
 */
function MemoryStorage(opts) { … }
```

2025-06-27 20:17 UTC, IamLizu commented on lib/multer-error.js
> +/**
maybe add an @extends Error tag so documentation tools know this class inherits from the built-in `Error`?

```js
/**
 * @extends Error
 * @param {string} code
 * @param {string} field
 */
function MulterError(code, field) { … }
```

2026-08-29 16:13 UTC, UlisesGascon commented
superseded by https://github.com/expressjs/multer/pull/1467

2026-08-29 16:13 UTC, closed without merging