Davidmashe/add formdata example
expressjs/multer pull request #896
Opened 2020-05-20 23:44 UTC by davidmashe

Adds new `examples` folder and a `FormData` example. Addresses #883

2020-06-10 21:31 UTC, jonchurch requested changes
Hey sorry this took so long to review! Thank you very much for working on this.

I think it needs a short readme, but this is a great start.

2020-06-11 00:59 UTC, davidmashe commented on examples/FormData/public/index.html
> +			const blob = new Blob([theText], { type: 'text/plain' });
what if have a second example with `new Image()` ?

2020-06-11 01:00 UTC, davidmashe commented on examples/FormData/package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
sure, can do

2020-06-11 01:00 UTC, davidmashe commented on examples/FormData/public/index.html
> +			.then(() => console.log('upload received'));
good ideas, will do

2020-06-25 01:22 UTC, davidmashe commented
Pushed update, added FormDataImage example and added improvements based on comments

2020-07-09 15:56 UTC, ghinks approved these changes
Good job, David.

2020-08-04 13:03 UTC, UlisesGascon approved these changes
Thanks a lot @davidmashe! 

LGTM 🚀

2020-08-05 00:18 UTC, davidmashe commented
Is this ok to merge?

2026-08-29 14:51 UTC, UlisesGascon approved these changes
I think that now is in a much better shape. @jonchurch can you have a lock and remove the blocker? 🙏

2026-08-29 21:50 UTC, bjohansebas approved these changes

2026-09-14 06:55 UTC, merged